// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("UniSpec")>]
[<assembly: AssemblyDescriptionAttribute("Base on gherkin syntax, coding step definition with F#")>]
[<assembly: AssemblyProductAttribute("UniSpec")>]
[<assembly: AssemblyCompanyAttribute("Eric")>]
[<assembly: AssemblyVersionAttribute("0.3.0")>]
[<assembly: AssemblyFileVersionAttribute("0.3.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.3.0")>]
[<assembly: InternalsVisibleToAttribute("UniSpec.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "UniSpec"
    let [<Literal>] AssemblyDescription = "Base on gherkin syntax, coding step definition with F#"
    let [<Literal>] AssemblyProduct = "UniSpec"
    let [<Literal>] AssemblyCompany = "Eric"
    let [<Literal>] AssemblyVersion = "0.3.0"
    let [<Literal>] AssemblyFileVersion = "0.3.0"
    let [<Literal>] AssemblyInformationalVersion = "0.3.0"
    let [<Literal>] InternalsVisibleTo = "UniSpec.Tests"
